"""
Unit and integration tests for Phase 4: Comparative RAG Evaluation Suite.
"""

import json
import sqlite3
import pytest
from pathlib import Path

from scripts.evaluate_rag import (
    compute_lexical_groundedness,
    compute_citation_source_accuracy,
    compute_faithfulness,
    compute_citation_correctness,
    format_markdown_report,
    RAGEvaluator,
    QueryEvalResult
)
from app.core.embedder import QueryEmbedder
from app.core.generator import Citation
from app.core.retriever import SearchResult


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATASET_PATH = PROJECT_ROOT / "data" / "eval_dataset.json"
DB_PATH = PROJECT_ROOT / "data" / "blogger.db"
BASELINE_DB_PATH = PROJECT_ROOT / "data" / "sample_wholedoc.db"
BASELINE_INDEX_PATH = PROJECT_ROOT / "indexes" / "faiss_sample_wholedoc.index"


def test_eval_dataset_schema_and_integrity():
    """Verify eval_dataset.json conforms to schema and all items map to real DB records."""
    assert DATASET_PATH.exists(), "eval_dataset.json must exist"

    with open(DATASET_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    assert "items" in data
    assert data["total_items"] >= 15
    assert data["in_domain_count"] > 0
    assert data["out_of_domain_count"] >= 2

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    for item in data["items"]:
        assert "id" in item
        assert "query" in item
        assert len(item["query"].strip()) > 5

        if item["is_out_of_domain"]:
            assert item["target_doc_id"] is None
            assert item["target_chunk_id"] is None
        else:
            cid = item["target_chunk_id"]
            did = item["target_doc_id"]
            exc = item["ground_truth_context"]

            cursor.execute("SELECT doc_id, content FROM documents WHERE id = ?", (cid,))
            row = cursor.fetchone()
            assert row is not None, f"Chunk {cid} not found in {DB_PATH}"
            assert row[0] == did, f"Doc ID mismatch for {cid}"

            content_clean = " ".join(row[1].split()).lower()
            exc_clean = " ".join(exc.split()).lower()
            assert exc_clean in content_clean, f"Context excerpt not in chunk {cid}"

    conn.close()


def test_wholedoc_baseline_artifacts():
    """Verify controlled whole-document baseline artifacts exist and are queryable."""
    assert BASELINE_INDEX_PATH.exists(), "Whole-doc FAISS index must exist"
    assert BASELINE_DB_PATH.exists(), "Whole-doc SQLite DB must exist"

    conn = sqlite3.connect(BASELINE_DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM documents")
    count = cursor.fetchone()[0]
    assert count == 4, "Expected exactly 4 whole documents in sample baseline"

    cursor.execute("SELECT id, doc_id, chunk_index, word_count FROM documents")
    rows = cursor.fetchall()
    for r in rows:
        assert r[0].endswith("_wholedoc")
        assert r[2] == 0
        assert r[3] > 1000  # Each whole document is > 1000 words

    conn.close()


def test_compute_lexical_groundedness_metric():
    """Test lexical groundedness scoring logic and deprecated faithfulness alias."""
    context = "RLAIF uses feedback generated by another AI instead of human evaluators to train language models."
    
    # High grounding
    grounded_ans = "RLAIF uses feedback generated by another AI system to train language models."
    score_high = compute_lexical_groundedness(grounded_ans, context, is_refused=False, is_ood=False)
    assert score_high > 0.70

    # Low grounding / hallucination
    hallucinated_ans = "Quantum computing requires cryogenic refrigerators and dilution cooling systems."
    score_low = compute_lexical_groundedness(hallucinated_ans, context, is_refused=False, is_ood=False)
    assert score_low < 0.20

    # Proper refusal on OOD query
    score_refused_ood = compute_lexical_groundedness("Refused answer", context, is_refused=True, is_ood=True)
    assert score_refused_ood == 1.0

    # Hallucinated response on OOD query (failed to refuse)
    score_unrefused_ood = compute_lexical_groundedness(hallucinated_ans, context, is_refused=False, is_ood=True)
    assert score_unrefused_ood == 0.0

    # Deprecated alias equivalence
    assert compute_faithfulness(grounded_ans, context, is_refused=False, is_ood=False) == score_high


def test_compute_citation_source_accuracy():
    """Test citation source accuracy scoring logic and deprecated citation_correctness alias."""
    passages = [
        SearchResult(
            chunk_id="chunk_1",
            doc_id="doc_A",
            chunk_index=0,
            title="Title A",
            url="http://a.com",
            author="Author",
            content="Direct Preference Optimization (DPO) simplifies LLM fine-tuning.",
            word_count=50,
            score=0.85,
            rank=1,
            faiss_id=0
        ),
        SearchResult(
            chunk_id="chunk_2",
            doc_id="doc_B",
            chunk_index=0,
            title="Title B",
            url="http://b.com",
            author="Author",
            content="Unrelated culinary recipes for baking bread.",
            word_count=40,
            score=0.30,
            rank=2,
            faiss_id=1
        )
    ]

    # Valid citation matching target doc
    cite_valid = [Citation(doc_tag="[Doc 1]", chunk_id="chunk_1", title="Title A", url="http://a.com", score=0.85)]
    score_valid = compute_citation_source_accuracy(cite_valid, target_doc_id="doc_A", passages=passages, keywords=["DPO"])
    assert score_valid == 1.0

    # Invalid citation pointing to wrong document
    cite_invalid = [Citation(doc_tag="[Doc 2]", chunk_id="chunk_2", title="Title B", url="http://b.com", score=0.30)]
    score_invalid = compute_citation_source_accuracy(cite_invalid, target_doc_id="doc_A", passages=passages, keywords=["DPO"])
    assert score_invalid == 0.0

    # Empty citations
    assert compute_citation_source_accuracy([], target_doc_id="doc_A", passages=passages, keywords=["DPO"]) == 0.0

    # Deprecated alias equivalence
    assert compute_citation_correctness(cite_valid, target_doc_id="doc_A", passages=passages, keywords=["DPO"]) == score_valid


def test_evaluator_single_query_smoke():
    """Verify RAGEvaluator single-query execution, fair k=3 default, shared embedder, and split latency."""
    evaluator = RAGEvaluator(embedder=QueryEmbedder("all-MiniLM-L6-v2"))
    sample_item = evaluator.eval_items[0]

    # Verify fair k=3 default
    assert evaluator.baseline_top_k == 3
    assert evaluator.final_top_k == 3

    # Verify shared embedder instance
    assert evaluator.baseline_retriever.embedder is evaluator.final_retriever.embedder

    b_res = evaluator.evaluate_query(sample_item, pipeline_type="baseline")
    assert isinstance(b_res, QueryEvalResult)
    assert b_res.pipeline == "baseline"
    assert b_res.context_chars > 5000  # Whole document context
    assert b_res.retrieval_latency_ms >= 0.0
    # In offline mode, generation and e2e latency must not be conflated with retrieval
    assert b_res.generation_latency_ms is None
    assert b_res.e2e_latency_ms is None

    f_res = evaluator.evaluate_query(sample_item, pipeline_type="final")
    assert isinstance(f_res, QueryEvalResult)
    assert f_res.pipeline == "final"
    assert f_res.context_chars < b_res.context_chars  # Chunks are significantly more compact
    assert f_res.top_score > 0.0
    assert f_res.lexical_groundedness > 0.0
    assert f_res.citation_source_accuracy >= 0.0
    # Check backward compatibility properties
    assert f_res.faithfulness == f_res.lexical_groundedness
    assert f_res.citation_correctness == f_res.citation_source_accuracy


def test_markdown_report_generation():
    """Verify format_markdown_report generates proper table, headers, methodology notes, and honest latency labels."""
    dummy_summary = {
        "dataset_info": {
            "total_queries": 2,
            "in_domain_queries": 2,
            "out_of_domain_queries": 0,
            "total_articles": 4,
            "total_chunks": 46,
            "baseline_top_k": 3,
            "final_top_k": 3,
            "similarity_threshold": 0.35,
            "evaluation_scope": "TEST_SCOPE",
            "evaluation_mode": "offline"
        },
        "baseline": {
            "granularity": "Whole Document",
            "doc_hit_rate": 0.50,
            "chunk_hit_rate": "N/A",
            "ood_refusal_rate": 1.0,
            "avg_retrieval_latency_ms": 10.5,
            "avg_generation_latency_ms": None,
            "avg_e2e_latency_ms": None,
            "avg_context_chars": 50000,
            "avg_context_tokens_est": 12500,
            "avg_lexical_groundedness": 0.65,
            "avg_citation_source_accuracy": 0.30
        },
        "final": {
            "granularity": "Chunked",
            "doc_hit_rate": 0.85,
            "chunk_hit_rate": 0.60,
            "ood_refusal_rate": 1.0,
            "avg_retrieval_latency_ms": 8.0,
            "avg_generation_latency_ms": None,
            "avg_e2e_latency_ms": None,
            "avg_context_chars": 7000,
            "avg_context_tokens_est": 1750,
            "avg_lexical_groundedness": 0.90,
            "avg_citation_source_accuracy": 0.85
        }
    }

    report = format_markdown_report(dummy_summary)
    assert "# Comparative RAG Evaluation Report" in report
    assert "Document Hit Rate" in report
    assert "86.0%" in report or "% context compression" in report
    assert "TEST_SCOPE" in report
    assert "Lexical Groundedness" in report
    assert "Citation Source Accuracy" in report
    assert "Whole-Document Truncation Effect" in report
    assert "N/A (Offline)" in report
