import os, nltk
import requests
from bs4 import BeautifulSoup
import time
import hashlib
import json
from langdetect import detect
from serper_api import google_search_serper
from tqdm import tqdm

# 1) NLTK setup
nltk.data.path.append(os.path.expanduser(r"~\AppData\Roaming\nltk_data"))
nltk.download('punkt',   quiet=True)
nltk.download('punkt_tab', quiet=True)

# 2) Fake browser headers to avoid 403s
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        " AppleWebKit/537.36 (KHTML, like Gecko)"
        " Chrome/115.0.0.0 Safari/537.36"
    )
}

visited_urls = set()
EXCLUDE_DOMAINS = [
    'google.',
    'facebook.',
    'instagram.',
    'youtube.',
    'quora.',
    'linkedin.',
    'pinterest.'
]
OUTPUT_PATH = "scraped_blogs_5.json"


# --- Helpers for outputting in a single JSON array, appending each entry ---

def append_result(entry):
    """
    Load the existing JSON array, append one entry, and rewrite the file.
    Creates the file with [entry] if it doesn't exist.
    """
    if os.path.exists(OUTPUT_PATH):
        with open(OUTPUT_PATH, "r+", encoding="utf-8") as f:
            try:
                data = json.load(f)
            except json.JSONDecodeError:
                data = []
            data.append(entry)
            f.seek(0)
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.truncate()
    else:
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            json.dump([entry], f, ensure_ascii=False, indent=2)

# --- Your existing helper functions remain unchanged ---

def is_english(text):
    try:
        return detect(text) == "en"
    except:
        return False

def is_excluded(url):
    return any(domain in url for domain in EXCLUDE_DOMAINS)

def extract_blog_content(url):
    try:
        resp = requests.get(url, headers=HEADERS, timeout=10)
        if resp.status_code != 200:
            print(f"→ {url} returned {resp.status_code}")
            return None, None

        soup = BeautifulSoup(resp.text, 'html.parser')
        text = " ".join(soup.stripped_strings)
        print(f"→ Fetched {len(text)} chars from {url}")

        tokens = nltk.word_tokenize(text)
        print(f"→ Token count: {len(tokens)}")

        if not is_english(text):
            print("   ✗ non-English")
            return None, None
        if len(tokens) < 300:
            print("   ✗ too short")
            return None, None

        title = soup.title.string.strip() if soup.title else ""
        return text, title

    except Exception as e:
        print(f"→ exception for {url}: {e!r}")
        return None, None


def google_search(query, num_pages=5):
    all_links = []
    for i in range(num_pages):
        paginated_query = f"{query} blog {i}"
        urls = google_search_serper(paginated_query)
        urls = [u for u in urls if not is_excluded(u)]
        all_links.extend(urls)
        time.sleep(1)
    return all_links

# --- Main scraping function, unchanged logic, only calls append_result() ---

def scrape_queries(queries, num_pages=5):
    total_saved = 0

    for query in queries:
        print(f"\n🔍 Query: {query}")
        urls = google_search(query, num_pages)
        rank = 1
        saved_count = 0

        for url in tqdm(urls,
                        desc=f"🔄 Processing blogs for: {query[:40]}",
                        ncols=100):
            url_hash = hashlib.md5(url.encode()).hexdigest()
            if url_hash in visited_urls:
                continue
            visited_urls.add(url_hash)

            text, title = extract_blog_content(url)
            if text:
                result = {
                    "query": query,
                    "title": title,
                    "url": url,
                    "content": text,
                    "rank": rank  
                }
                append_result(result)   # <-- Appends into a single JSON array file
                print(f"✅ Saved: {title[:60]}...")
                rank += 1
                saved_count += 1
                total_saved += 1
            else:
                print(f"❌ Skipped: {url[:60]}...")

            time.sleep(1)

        print(f"📦 Blogs saved for this query: {saved_count}")
        print(f"📊 Total blogs scraped so far: {total_saved}")


# Run script
if __name__ == "__main__":

    test_queries = [
    "Reinforcement Learning from AI Feedback (RLAIF) production guide",
    "real-world challenges in RLAIF implementation",
    "best practices for Reinforcement Learning from AI Feedback",
    "RLAIF deep dive: architecture patterns and insights",
    "practical guide to Reinforcement Learning from AI Feedback",
    "intuition behind RLAIF: a visual explanation",
    "self-supervised learning for large language models: a production guide",
    "real-world challenges in self-supervised LLM pre-training",
    "best practices for self-supervised learning with LLMs",
    "deep dive into self-supervised learning architectures for LLMs",
    "practical guide to self-supervised learning for large language models",
    "contrastive learning for LLM pre-training: a deep dive",
    "architecture patterns in contrastive learning for LLMs",
    "practical guide to contrastive learning for language models",
    "intuition behind contrastive learning for LLMs",
    "generative AI for code generation and completion: production guide",
    "real-world challenges in generative AI for coding",
    "best practices for generative AI code tools",
    "deep dive into generative AI architectures for code",
    "AI for scientific discovery (drug design): a practical guide",
    "real-world challenges in AI for materials science",
    "best practices in AI for drug design",
    "deep dive into AI for scientific discovery platforms",
    "program synthesis with LLMs: architectural patterns and challenges",
    "practical guide to program synthesis using large language models",
    "intuition behind LLM-based program synthesis",
    "visual explanation of embodied AI agents",
    "embodied AI agents: real-world challenges and solutions",
    "best practices for developing embodied AI",
    "deep dive into embodied AI architectures",
    "tool use in LLMs: a comprehensive explanation",
    "practical guide to implementing tool use in large language models",
    "intuition behind LLM tool integration",
    "multimodal AI applications in healthcare: production guide",
    "real-world challenges for multimodal AI in robotics",
    "best practices for multimodal AI in healthcare",
    "deep dive into multimodal AI architectures for robotics",
    "agentic AI and human-agent collaboration: best practices guide",
    "real-world challenges in human-agent collaboration",
    "deep dive into agentic AI frameworks",
    "practical guide to designing human-agent collaborative systems",
    "adversarial attacks and defense strategies: a deep dive",
    "practical guide to defending against adversarial attacks",
    "intuition behind adversarial examples",
    "visual explanation of adversarial attack techniques",
    "out-of-distribution (OOD) detection: real-world challenges",
    "best practices for OOD detection in deep learning",
    "deep dive into OOD detection algorithms",
    "practical guide to uncertainty quantification in deep learning",
    "mathematical derivation of uncertainty in neural networks",
    "intuition behind uncertainty quantification",
    "explainable AI (XAI) for critical applications (healthcare): production guide",
    "real-world challenges in XAI for finance",
    "best practices for Explainable AI in critical systems",
    "deep dive into XAI methods for healthcare",
    "bias detection and mitigation in AI systems: practical guide",
    "real-world challenges in AI fairness",
    "best practices for bias mitigation in machine learning",
    "deep dive into fairness algorithms in AI",
    "privacy-preserving AI techniques (Federated Learning): production guide",
    "real-world challenges in Differential Privacy for AI",
    "best practices for Homomorphic Encryption in machine learning",
    "deep dive into privacy-preserving AI architectures",
    "AI alignment problem: a comprehensive explanation",
    "responsible AI development frameworks: practical guide",
    "real-world challenges in AI governance",
    "best practices for responsible AI deployment",
    "auditing black-box models: a practical guide",
    "deep dive into black-box model auditing techniques",
    "intuition behind model interpretability for auditing",
    "continual learning to mitigate catastrophic forgetting: deep dive",
    "practical guide to lifelong learning AI systems",
    "intuition behind catastrophic forgetting in neural networks",
    "visual explanation of continual learning strategies",
    "meta-learning (learning to learn): architectural patterns",
    "practical guide to meta-learning algorithms",
    "intuition behind learning to learn",
    "online vs. Batch learning: a practical comparison guide",
    "real-world challenges in online learning systems",
    "best practices for batch learning optimization",
    "curriculum learning strategies: deep dive into applications",
    "practical guide to curriculum learning in deep learning",
    "intuition behind curriculum design for AI models",
    "knowledge distillation for model compression: production guide",
    "real-world challenges in knowledge distillation",
    "best practices for model compression via distillation",
    "deep dive into knowledge distillation techniques",
    "transfer learning beyond fine-tuning: advanced techniques",
    "practical guide to advanced transfer learning",
    "intuition behind sophisticated transfer learning",
    "self-supervised learning applications in industry: real-world examples",
    "deep dive into industrial self-supervised learning use cases",
    "best practices for deploying self-supervised models in production",
    "zero-shot and few-shot learning advancements: a comprehensive guide",
    "practical guide to zero-shot learning applications",
    "intuition behind few-shot learning capabilities",
    "Graph Neural Networks (GNNs) in production: challenges and solutions",
    "deep dive into GNN architectures for real-world applications",
    "best practices for deploying GNNs",
    "time series forecasting with deep learning: production guide",
    "real-world challenges in deep learning for time series",
    "best practices for time series forecasting models",
    "Reinforcement Learning in robotics and game AI: practical guide",
    "real-world challenges in RL for robotics",
    "best practices for RL in game AI",
    "ML for recommender systems advancements: deep dive",
    "real-world challenges in ML for recommenders",
    "best practices for building robust recommender systems",
    "Causal ML for robust decision making: practical guide",
    "intuition behind causal inference in machine learning",
    "deep dive into causal ML algorithms",
    "Event-based vision in AI: a practical guide",
    "real-world challenges in event-based vision systems",
    "deep dive into event cameras and AI",
    "Protein folding with AI (e.g., AlphaFold insights): deep dive",
    "practical guide to AI in protein science",
    "intuition behind AlphaFold breakthroughs",
    "Material science applications of AI: production guide",
    "real-world challenges in AI for materials discovery",
    "best practices for AI in materials research",
    "Climate modeling with deep learning: a practical guide",
    "real-world challenges in deep learning for climate science",
    "best practices for climate modeling with AI",
    "Data centric AI development: best practices guide",
    "real-world challenges in data-centric AI",
    "deep dive into data-centric AI methodologies",
    "Feature stores for MLOps: a practical guide",
    "real-world challenges in MLOps feature management",
    "best practices for feature store implementation",
    "Model serving infrastructure (e.g., Triton Inference Server): deep dive",
    "practical guide to model serving with Triton Inference Server",
    "real-world challenges in high-performance model serving",
    'Supervised Learning production guide with real-world applications',
    'Practical deep dive into Unsupervised Learning architecture patterns',
    'Semi-Supervised Learning explained from scratch implementation',
    'Reinforcement Learning case study: production challenges and solutions',
    'Regression Analysis best practices for industry-grade models',
    'Classification visual explanation and intuition behind decision boundaries',
    'Clustering real-world challenges and effective architecture patterns',
    'Dimensionality Reduction explained: a mathematical derivation overview',
    'Feature Engineering practical guide with production-ready patterns',
    'Feature Selection deep dive: best practices and case studies',
    'Model Evaluation Metrics from scratch: explained with examples',
    'Cross-Validation production guide and real-world pitfalls',
    'Hyperparameter Tuning case study: tuning random forest in finance',
    'Overfitting and Underfitting illustrated with visual examples',
    'Bias-Variance Tradeoff intuition behind and practical remedies',
    'Ensemble Methods architecture patterns: bagging vs boosting vs stacking',
    'Bagging deep dive: real-world use cases and best practices',
    'Boosting explained: gradient boosting from scratch implementation',
    'Stacking practical guide: architecture patterns and pitfalls',
    'Meta-Learning production guide: deploying meta-models at scale',
    'Transfer Learning case study: fine-tuning transformers in NLP',
    'Active Learning explained: intuition and production roadmap',
    'Online Learning best practices: streaming data implementation',
    'Federated Learning deep dive: privacy-preserving architecture patterns',
    'Few-Shot Learning practical guide with industry examples',
    'Zero-Shot Learning explained from scratch and real-world challenges',
    'Self-Supervised Learning case study: vision transformer pretraining',
    'Anomaly Detection production guide: implementation with autoencoders',
    'Recommender Systems best practices: architecture and evaluation',
    'Time Series Forecasting practical guide: from data prep to deployment',
    'Linear Regression intuitive explanation and mathematical derivation',
    'Logistic Regression deep dive: real-world classification challenges',
    'Decision Trees explained visually: from scratch to production',
    'Random Forest case study: improving model robustness in banking',
    'Support Vector Machines (SVM) intuition behind and mathematical proof',
    'k-Nearest Neighbors (kNN) practical guide: tuning for performance',
    'Naive Bayes explained: probabilistic foundations and case studies',
    'k-Means Clustering deep dive: initialization tricks and pitfalls',
    'Hierarchical Clustering practical guide: dendrogram interpretation',
    'DBSCAN real-world challenges and architecture patterns',
    'PCA (Principal Component Analysis) explained visually and mathematically',
    't-SNE deep dive: visual explanation and production considerations',
    'UMAP practical guide: dimensionality reduction for embeddings',
    'LDA (Linear Discriminant Analysis) intuition and case studies',
    'End-to-End ML Architecture patterns: production guide',
    'Data Pipeline Best Practices for Machine Learning production',
    'Feature Store design: real-world challenges and solutions',
    'Model Monitoring deep dive: production-grade metrics and alerts',
    'MLOps case study: CI/CD for ML with best practices',
    'Explainable AI (XAI) practical guide: techniques and architecture',
    'Model Interpretability real-world challenges and solutions',
    'ML Lifecycle best practices: from data collection to deployment',
    'Data Drift detection explained with case studies',
    'Concept Drift adaptation: deep dive into strategies',
    'Hyperparameter Optimization frameworks: production guide',
    'Neural Network regularization techniques: best practices',
    'Convolutional Neural Networks explained visually and mathematically',
    'Recurrent Neural Networks deep dive: architecture patterns',
    'Transformer models practical guide: from scratch implementation',
    'Attention Mechanism intuition behind and case study',
    'GANs (Generative Adversarial Networks) explained with examples',
    'Autoencoder case study: anomaly detection in manufacturing',
    'Graph Neural Networks practical guide and real-world use cases',
    'Bayesian Methods deep dive: from theory to production',
    'Markov Decision Processes explained: reinforcement learning foundation',
    'Q-Learning architecture patterns and best practices',
    'Policy Gradient methods real-world challenges and solutions',
    'Deep Q-Networks (DQN) explained: case study and mathematical derivation',
    'Actor-Critic algorithms practical guide: intuition and implementation',
    'Multi-Armed Bandits deep dive: exploration vs exploitation',
    'Time Series Anomaly Detection best practices and case studies',
    'Sequence Modeling explained visually: RNN vs Transformer',
    'Multimodal Learning production guide: combining text and images',
    'Imbalanced Data handling: practical guide and best practices',
    'Data Augmentation techniques deep dive: case study in computer vision',
    'Feature Scaling importance explained: from scratch to production',
    'Embedding Representations practical guide: word2vec to BERT',
    'Topic Modeling case study: LDA vs LSI vs NMF',
    'Natural Language Processing pipeline best practices',
    'Speech Recognition deep dive: end-to-end architecture patterns',
    'Computer Vision real-world challenges: object detection case study',
    'Semantic Segmentation practical guide: U-Net architecture',
    'Pose Estimation explained visually and mathematically',
    'Reinforcement Learning in Robotics: case study and best practices',
    'Explainability in Deep Learning deep dive: SHAP and LIME',
    'Optimization Algorithms practical guide: SGD, Adam, and beyond',
    'Learning Rate Schedules explained: warm-up, decay, and case studies',
    'Batch Normalization intuition behind and production considerations',
    'Dropout regularization deep dive: theory and practice',
    'Early Stopping explained: when and how to use',
    'Model Compression best practices: quantization and pruning',
    'Distillation of Neural Networks case study: student-teacher models',
    'Privacy in ML deep dive: differential privacy techniques',
    'Adversarial Attacks and Defenses practical guide',
    'Robustness Evaluation explained: adversarial testing pipelines',
    'Ethics in AI case study: real-world incidents and lessons',
    'Sustainability in ML best practices: green AI guide',
    'ML Infrastructure deep dive: Kubernetes for model serving',
    'Feature Stores explained: architecture and implementation guide',
    'Continuous Training pipeline practical guide: automated model updates',
    'How QDA works in real-world industry applications',
    'Intuitive explanation of Gradient Descent with visuals',
    'Stochastic Gradient Descent: when and why it fails',
    'Adagrad optimizer vs Adam in production ML systems',
    'Mastering RMSprop: best practices from practitioners',
    'Adam Optimizer deep dive for tuning and convergence',
    'Genetic Algorithms for hyperparameter search explained',
    'Real-world uses of Simulated Annealing in optimization',
    'Visual guide to Particle Swarm Optimization in ML',
    'Bayesian Optimization in large-scale ML workflows',
    'Gaussian Processes practical guide for beginners',
    'Hidden Markov Models explained with industry examples',
    'Conditional Random Fields: decoding sequence modeling',
    'Monte Carlo Tree Search in games and robotics',
    'Expectation-Maximization: visual breakdown & math',
    'ANN vs CNN vs RNN: architecture comparison guide',
    'MLP explained: intuition and math behind feedforward nets',
    'CNN architecture breakdown for visual learners',
    'How Recurrent Neural Networks are used in NLP tasks',
    'LSTM vs GRU: what to use and when',
    'Transformer models: production-ready implementation tips',
    'Inside Attention Mechanisms: visual and math explanation',
    'Understanding BERT with contextual use-cases',
    'GPT models: architecture, limitations and fine-tuning',
    'T5 transformer explained from training to inference',
    'Vision Transformers (ViT) real-world deployment guide',
    'Graph Neural Networks: applications and real case studies',
    'Capsule Networks vs CNNs: structural comparison',
    'Siamese Networks for face recognition: deep dive',
    'Autoencoders in anomaly detection: practical use cases',
    'Variational Autoencoders intuition and math explained',
    'Training GANs: best practices and troubleshooting',
    'Self-Organizing Maps explained through real data',
    'Neural ODEs: the math and intuition you need',
    'Deep Reinforcement Learning: how to scale in practice',
    'DQN vs Policy Gradient: real-world comparison',
    'Actor-Critic methods in high-dimensional RL environments',
    'QDA explained visually with decision boundaries',
    'Gradient Descent optimization patterns in deep networks',
    'Stochastic Gradient Descent real-world challenges',
    'Implementing Adagrad from scratch in Python',
    'Why RMSprop works well for non-convex problems',
    'Adam optimizer: intuition and tuning strategies',
    'Evolutionary search with Genetic Algorithms: case studies',
    'Simulated Annealing: deep dive with code examples',
    'How Particle Swarm Optimization solves engineering tasks',
    'Bayesian Optimization for tuning deep neural networks',
    'Gaussian Processes explained for developers',
    'HMMs for time series: best practices',
    'Conditional Random Fields vs HMMs: comparative blog',
    'Monte Carlo Tree Search: from game AI to robotics',
    'Expectation-Maximization: theory and implementation',
    'Neural Networks: production-level pitfalls and patterns',
    'Understanding MLPs through toy datasets',
    'CNN kernels explained visually',
    'RNNs explained with simple sequence examples',
    'LSTM networks for time series prediction: case study',
    'GRU explained via interactive visual blog',
    'Transformer internals: from attention to heads',
    'Attention in deep learning: code and explanation',
    'Understanding BERT embeddings: visual walkthrough',
    'GPT fine-tuning tips for domain-specific applications',
    'T5 vs BERT: use-case based comparison',
    'Vision Transformer vs CNNs: when to switch',
    'Graph Neural Networks for recommender systems',
    'Capsule Networks explained through animations',
    'Siamese Network applications in e-commerce',
    'Autoencoders for dimensionality reduction: best blogs',
    'VAE loss function explained intuitively',
    'GANs: failure modes and debugging techniques',
    'Self-Organizing Maps for clustering: explained',
    'Neural ODEs practical guide with examples',
    'Deep RL success stories in industry',
    'Why DQNs fail in complex environments',
    'Actor-Critic vs A2C vs PPO: breakdown and trade-offs',
    'Quadratic Discriminant Analysis in high-dim space',
    'Gradient Descent visual guide for learning rate effects',
    'SGD tweaks that improve convergence',
    'Adagrad vs RMSprop vs Adam: comparison cheat sheet',
    'When not to use Adam Optimizer',
    'Genetic Algorithms vs Backpropagation: use-case focus',
    'Simulated Annealing coding walkthrough',
    'PSO for ML hyperparameter optimization',
    'Bayesian Optimization tricks from Kaggle winners',
    'Gaussian Processes for uncertainty modeling',
    'Hidden Markov Models in speech recognition',
    'CRFs explained for structured prediction tasks',
    'MCTS for decision making under uncertainty',
    'Expectation-Maximization for clustering: step by step',
    'ANNs vs MLPs vs CNNs vs RNNs explained',
    'MLP for tabular data: modern applications',
    'CNNs for feature extraction: production tips',
    'RNN attention mechanism explained',
    'LSTM gates explained using animations',
    'GRU vs LSTM: performance benchmarks',
    'Transformers in production: optimization techniques',
    'Attention visualization tools for NLP',
    'Pretraining vs fine-tuning BERT: what matters more?',
    'GPT as few-shot learners: case-based blog',
    'T5 model architecture: from paper to code',
    'Vision Transformer use in real-time systems',
    'Graph Neural Networks for fraud detection',
    'Capsule Networks for spatial hierarchy learning',
    'Siamese architecture in low-data regimes',
    'Autoencoders for denoising: illustrated guide',
    'VAE sampling and KL divergence explained',
    'How to train stable GANs: checklist',
    'Neural ODE applications in scientific ML',
    'Deep Q-Networks code + explanation combo',
    'Policy Gradient debugging and logging tips',
    'End-to-end Actor-Critic pipeline in production',
    'Deep Belief Networks production guide',
    'Deep Belief Networks real-world challenges',
    'Deep Belief Networks architecture patterns explained',
    'intuition behind Deep Belief Networks',
    'visual explanation of Deep Belief Networks',
    'Restricted Boltzmann Machines best practices',
    'RBM deep dive for practitioners',
    'practical guide to Restricted Boltzmann Machines',
    'Residual Networks for industry applications',
    'ResNet architecture patterns explained',
    'ResNet real-world implementation challenges',
    'DenseNet production deployment insights',
    'DenseNet practical guide for engineers',
    'intuition behind DenseNet architecture',
    'Inception Networks best practices production',
    'Inception Networks deep dive explained',
    'real-world applications of Inception Networks',
    'YOLO Object Detection production guide',
    'YOLO Object Detection real-world challenges',
    'YOLO Object Detection architecture explained for practitioners',
    'SSD (Single Shot MultiBox Detector) best practices',
    'SSD for practical object detection',
    'U-Net Segmentation production deployment',
    'U-Net Segmentation architecture deep dive',
    'Mask R-CNN real-world applications',
    'Mask R-CNN explained for practitioners',
    'Semantic Segmentation practical guide',
    'Semantic Segmentation beyond the basics',
    'Instance Segmentation best practices production',
    'Super-Resolution engineering insights',
    'Neural Style Transfer practical applications',
    'Image Captioning production guide',
    'Speech Recognition real-world challenges',
    'Text-to-Speech (TTS) architecture patterns',
    'Natural Language Processing (NLP) best practices production',
    'Computer Vision industry examples',
    'Speech Processing engineering insights',
    'Audio Signal Processing practical guide',
    'RL in Robotics real-world challenges',
    'Graph Machine Learning production guide',
    'Causal Inference practical applications',
    'Bayesian Machine Learning deep dive',
    'Explainable AI (XAI) for practitioners',
    'Interpretable ML intuition behind',
    'Ethical AI beyond the basics',
    'Fairness in AI real-world examples',
    "Deep Belief Networks in industry: a practitioner's guide",
    'Mastering RBM: a deep dive for real-world scenarios',
    'Unlocking the power of ResNet: an engineering perspective',
    'DenseNet explained: architecture, implementation, and challenges',
    'Inception Networks: from theory to production',
    'YOLO Object Detection: practical guide and best practices',
    'SSD for production-grade object detection: a deep dive',
    'U-Net Segmentation: visual explanation and practical insights',
    'Mask R-CNN in the wild: industry applications and challenges',
    "Semantic Segmentation: a practitioner's guide to advanced techniques",
    'Instance Segmentation: beyond the basics with real-world examples',
    'Super-Resolution for practical applications: engineering insights',
    'Neural Style Transfer: deep dive into artistic AI',
    'Image Captioning: building production-ready systems',
    'Speech Recognition: real-world challenges and solutions',
    'Text-to-Speech (TTS): architecture patterns and practical tips',
    'Natural Language Processing (NLP): best practices for industry',
    'Computer Vision: industry examples and emerging trends',
    'Speech Processing: engineering insights for practical systems',
    'Audio Signal Processing: a practical guide for machine learning',
    'Reinforcement Learning in Robotics: real-world applications',
    'Graph Machine Learning: a production guide for practitioners',
    'Causal Inference: practical applications and intuition',
    'Bayesian Machine Learning: a deep dive for engineers',
    'Explainable AI (XAI): beyond the basics for practitioners',
    'Interpretable ML: visual explanations and practical guides',
    'Ethical AI: real-world challenges and solutions',
    'Fairness in AI: industry examples and best practices',
    'Deep Belief Networks: practical implementation for production',
    'Restricted Boltzmann Machines: real-world use cases explained',
    'Residual Networks: engineering insights into scalable architectures',
    'DenseNet explained: visual intuition and practical implementation',
    'Inception Networks: deep dive into architectural patterns',
    'YOLO Object Detection: from scratch implementation and optimization',
    'SSD (Single Shot MultiBox Detector): mathematical derivation and practical guide',
    'U-Net Segmentation: best practices for medical imaging',
    'Mask R-CNN: production deployment challenges and solutions',
    'Semantic Segmentation: advanced techniques for real-world data',
    'Instance Segmentation: a comprehensive guide for practitioners',
    'Super-Resolution: beyond the basics with practical examples',
    'Neural Style Transfer: an engineering deep dive',
    'Image Captioning: real-world performance benchmarks',
    'Speech Recognition: best practices for low-resource languages',
    'Text-to-Speech (TTS): practical guide to voice cloning',
    'Natural Language Processing (NLP): real-world challenges in industry',
    'Computer Vision: practical guide to adversarial attacks',
    'Speech Processing: intuition behind spectrograms and audio features',
    'Audio Signal Processing: deep dive into real-time applications',
    'RL in Robotics: practical guide to simulation and transfer learning',
    'Graph Machine Learning: real-world applications in finance',
    'Causal Inference: industry examples and challenges',
    'Bayesian Machine Learning: practical guide to probabilistic programming',
    'Explainable AI (XAI): real-world impact and ethical considerations',
    'Interpretable ML: beyond the basics with practical examples',
    'Ethical AI: framework for responsible AI development',
    'Fairness in AI: practical guide to bias detection and mitigation',
    'capsule networks routing algorithm intuition behind geometric understanding',
    'implementing capsule networks from scratch dynamic routing explained',
    'why capsule networks failed production challenges real world analysis',
    'siamese network architecture deep dive contrastive loss mathematical derivation',
    'one shot learning siamese networks practical implementation guide',
    'triplet loss vs contrastive loss siamese networks production best practices',
    'variational autoencoder reparameterization trick mathematical intuition explained',
    'autoencoder latent space representation learning visual guide',
    'VAE decoder architecture design patterns production deployment',
    'beta-VAE disentangled representation learning theoretical foundation',
    'GAN training instability mode collapse practical solutions engineering',
    'progressive GAN architecture scaling high resolution image generation',
    'Wasserstein GAN mathematical foundation Lipschitz constraint explained',
    'StyleGAN latent space manipulation techniques production implementation',
    'self organizing maps competitive learning algorithm visualization techniques',
    'SOM neighborhood function topology preservation mathematical analysis',
    'neural ordinary differential equations continuous normalizing flows explained',
    'adjoint sensitivity method neural ODEs computational efficiency',
    'neural ODE memory efficiency reverse mode differentiation',
    'deep Q learning experience replay importance sampling theoretical justification',
    'policy gradient REINFORCE algorithm variance reduction techniques',
    'actor critic advantage estimation bias variance tradeoff',
    'PPO clipped surrogate objective function mathematical derivation',
    'DDPG continuous action space exploration strategies',
    'restricted Boltzmann machine contrastive divergence training algorithm',
    'deep belief networks layer wise pretraining why it works',
    'RBM energy function probabilistic interpretation',
    'ResNet skip connections vanishing gradient problem mathematical analysis',
    'DenseNet feature reuse computational efficiency trade offs',
    'inception network factorized convolutions design principles',
    'residual connections identity mapping theoretical foundation',
    'YOLO anchor box design non maximum suppression implementation details',
    'single shot detector feature pyramid networks architectural insights',
    'region proposal networks RPN anchor generation strategy',
    'focal loss class imbalance one stage detectors',
    'U-Net skip connections semantic segmentation medical imaging applications',
    'Mask R-CNN RoIAlign feature alignment pixel level accuracy',
    'semantic vs instance segmentation architectural differences',
    'fully convolutional networks transpose convolution upsampling',
    'super resolution perceptual loss function vs pixel loss comparison',
    'neural style transfer Gram matrix texture representation',
    'image captioning attention mechanism visual transformer architecture',
    'connectionist temporal classification CTC loss speech recognition',
    'mel spectrogram feature extraction speech processing pipeline',
    'WaveNet dilated convolutions autoregressive audio generation',
    'attention based speech recognition end to end training',
    'transformer attention mechanism self attention mathematical foundation',
    'BERT bidirectional encoding masked language modeling explained',
    'vision transformer patch embedding positional encoding',
    'convolutional neural networks translation equivariance property',
    'graph neural networks message passing aggregation functions',
    'causal inference machine learning Pearl causal hierarchy',
    'Bayesian neural networks uncertainty quantification Monte Carlo dropout',
    'variational Bayes neural networks posterior approximation',
    'SHAP values game theory feature importance explanation',
    'LIME local interpretable model agnostic explanations',
    'integrated gradients attribution methods deep networks',
    'counterfactual explanations algorithmic recourse',
    'algorithmic bias fairness metrics equalized odds demographic parity',
    'differential privacy machine learning privacy preserving techniques',
    'adversarial examples robustness evaluation defense mechanisms',
    'federated learning privacy preserving distributed training',
    'quantum machine learning variational quantum circuits NISQ era',
    'quantum neural networks parameter initialization strategies',
    'TinyML model compression quantization edge deployment',
    'knowledge distillation teacher student network compression',
    'distributed deep learning parameter server architecture',
    'gradient compression distributed training communication efficiency',
    'data parallelism vs model parallelism scaling strategies',
    'PyTorch dynamic computation graph vs TensorFlow static graph',
    'ONNX model interoperability production deployment pipeline',
    'JAX functional programming automatic differentiation',
    'TensorFlow Serving model versioning A/B testing',
    'machine learning model serving infrastructure design patterns',
    'ML model monitoring drift detection production systems',
    'feature store architecture real time inference pipeline',
    'continuous training MLOps pipeline automation',
    'model versioning experiment tracking production best practices',
    'A/B testing machine learning models statistical significance',
    'machine learning system design interview preparation',
    'data pipeline architecture batch vs streaming processing',
    'information theory mutual information representation learning',
    'optimal transport Wasserstein distance machine learning applications',
    'spectral normalization GAN training stability theoretical analysis',
    'batch normalization internal covariate shift hypothesis debunked',
    'dropout regularization Bayesian interpretation uncertainty estimation',
    'reinforcement learning robotics sim to real transfer',
    'multi agent reinforcement learning Nash equilibrium game theory',
    'meta learning few shot learning MAML algorithm explained',
    'continual learning catastrophic forgetting mitigation strategies',
    'domain adaptation unsupervised domain transfer techniques',
    'transformer decoder only vs encoder decoder architectures',
    'mixture of experts sparse neural networks computational efficiency',
    'neural architecture search differentiable architecture search',
    'capsule networks equivariance vs convolutional networks',
    'focal loss class imbalance hard negative mining',
    'triplet loss mining strategies online hard negative sampling',
    'Adam optimizer bias correction momentum decay analysis',
    'learning rate scheduling warmup cosine annealing strategies',
    'normalizing flows invertible neural networks likelihood estimation',
    'energy based models contrastive divergence Langevin dynamics',
    'diffusion models score matching denoising probabilistic models',
    'autoregressive models PixelCNN masked attention mechanisms',
    'cross validation time series data temporal dependencies',
    'precision recall F1 score class imbalanced datasets',
    'ROC AUC interpretation binary classification thresholds',
    'statistical significance machine learning experiments multiple testing',
    'data augmentation techniques computer vision regularization effect',
    'feature engineering automated feature selection methods',
    'handling missing data imputation vs deletion strategies',
    'outlier detection isolation forest vs one class SVM',
    'distributed tensorflow training architecture patterns production environments',
    'pytorch ddp vs horovod performance comparison real world benchmarks',
    'implementing parameter servers from scratch distributed deep learning',
    'gradient compression techniques sparse communication distributed training',
    'asynchronous vs synchronous sgd mathematical analysis production trade-offs',
    'fault tolerance mechanisms distributed machine learning systems design',
    'data parallelism vs model parallelism architectural decisions large models',
    'tensorflow mesh implementation guide tensor sharding strategies',
    'pytorch lightning fabric distributed training best practices',
    'ray tune hyperparameter optimization distributed computing clusters',
    'kubeflow pipelines ml workflows kubernetes production deployment patterns',
    'mlflow model registry versioning strategies enterprise environments',
    'dvc data lineage tracking large scale ml projects',
    'apache airflow ml pipeline orchestration scheduling patterns',
    'weights biases experiment tracking distributed training visualization',
    'neptune ml metadata management team collaboration workflows',
    'spark mllib distributed feature engineering pipeline optimization',
    'hugging face transformers multi gpu training memory optimization',
    'jax sharding api distributed training functional programming approach',
    'onnx model interoperability deployment across frameworks',
    'tfx pipeline components production ml system architecture',
    'neural architecture search distributed computing resource allocation',
    'automl bayesian optimization distributed hyperparameter tuning',
    'continual learning catastrophic forgetting mitigation strategies',
    'meta learning few shot adaptation distributed environments',
    'sparse neural networks pruning techniques inference acceleration',
    'spiking neural networks temporal processing energy efficiency',
    'neuro symbolic reasoning integration deep learning knowledge graphs',
    'embodied ai simulation distributed reinforcement learning',
    'federated learning privacy preserving distributed training',
    'model serving infrastructure kubernetes istio traffic management',
    'feature stores real time inference batch processing architecture',
    'ml observability monitoring distributed training job failures',
    'data drift detection production ml model performance degradation',
    'a/b testing ml models statistical significance distributed systems',
    'gradient accumulation memory constrained distributed training',
    'mixed precision training fp16 distributed performance optimization',
    'allreduce algorithms ring vs tree topology performance analysis',
    'parameter server vs all reduce communication patterns comparison',
    'dynamic batching inference optimization distributed serving',
    'model compression quantization distributed edge deployment',
    'pipeline parallelism transformer models memory bandwidth optimization',
    'tensor parallelism large language models distributed inference',
    'activation checkpointing memory optimization distributed training',
    'elastic training dynamic resource allocation kubernetes clusters',
    'spot instance training cost optimization fault recovery strategies',
    'multi node multi gpu training network topology considerations',
    'rdma infiniband high performance computing ml workloads',
    'container orchestration ml workloads resource scheduling',
    'distributed data loading bottlenecks io optimization strategies',
    'model sharding strategies large transformer architectures',
    'gradient clipping distributed training stability techniques',
    'learning rate scheduling distributed training convergence analysis',
    'batch normalization distributed training synchronization issues',
    'distributed optimizer states adam momentum synchronization',
    'checkpoint restart mechanisms distributed training reliability',
    'load balancing strategies distributed inference serving',
    'auto scaling ml workloads kubernetes horizontal pod autoscaler',
    'distributed hyperparameter optimization population based training',
    'multi objective optimization distributed neural architecture search',
    'reinforcement learning distributed environments sample efficiency',
    'distributed graph neural networks large scale graph processing',
    'federated optimization non iid data distribution challenges',
    'differential privacy distributed machine learning privacy budgets',
    'secure aggregation federated learning cryptographic protocols',
    'communication compression distributed training convergence guarantees',
    'byzantine fault tolerance distributed learning adversarial nodes',
    'consensus algorithms distributed parameter updates blockchain integration',
    'distributed feature selection large scale dimensionality reduction',
    'online learning distributed streaming data concept drift',
    'ensemble methods distributed training model diversity optimization',
    'knowledge distillation distributed teacher student training',
    'transfer learning distributed fine tuning large pretrained models',
    'few shot learning distributed meta learning optimization',
    'zero shot learning distributed representation learning',
    'self supervised learning distributed contrastive learning',
    'generative adversarial networks distributed training stability',
    'variational autoencoders distributed latent space learning',
    'attention mechanisms distributed transformer training efficiency',
    'recurrent neural networks distributed sequence modeling',
    'convolutional networks distributed image processing pipelines',
    'graph convolutional networks distributed node classification',
    'temporal convolutional networks distributed time series analysis',
    'capsule networks distributed routing algorithms',
    'neural ordinary differential equations distributed continuous learning',
    'normalizing flows distributed density estimation',
    'energy based models distributed sampling strategies',
    'bayesian neural networks distributed uncertainty quantification',
    'gaussian processes distributed scalable approximations',
    'kernel methods distributed large scale kernel machines',
    'support vector machines distributed optimization algorithms',
    'decision trees distributed random forest implementations',
    'clustering algorithms distributed k means mapreduce',
    'dimensionality reduction distributed pca svd implementations',
    'anomaly detection distributed outlier identification',
    'recommendation systems distributed collaborative filtering',
    'natural language processing distributed transformer training',
    'computer vision distributed image classification pipelines',
    'speech recognition distributed acoustic modeling',
    'time series forecasting distributed lstm training',
    'reinforcement learning distributed policy gradient methods',
    'multi agent systems distributed coordination algorithms',
    'robotics distributed perception action learning',
    'autonomous vehicles distributed sensor fusion',
    'healthcare ai distributed federated learning privacy',
    'finance ai distributed fraud detection real time',
    'retail ai distributed recommendation systems personalization',
    'manufacturing ai distributed predictive maintenance',
    'energy systems distributed smart grid optimization',
    'configurable ML pipelines production guide',
    'low-latency inference best practices for real-time systems',
    'training vs inference tradeoffs in scalable ML architecture patterns',
    'real-time system design for machine learning explained',
    'debugging edge cases in production ML systems deep dive',
    'scalable system design for machine learning practical guide',
    'cross-domain applications of AI real-world challenges',
    'impact analysis of model changes in production',
    'data-centric challenges in enterprise AI architectures',
    'training stability issues in deep learning best practices',
    'hyperparameter tuning guide for production models',
    'robustness in production ML systems architectural patterns',
    'ML system reliability end-to-end deployment guide',
    'architecting for maintainability in machine learning pipelines',
    'transfer learning production guide',
    'active learning practical guide for data scientists',
    'online learning real-world challenges and solutions',
    'federated learning architecture patterns explained',
    'few-shot learning intuition behind and applications',
    'zero-shot learning deep dive and visual explanation',
    'self-supervised learning from scratch implementation',
    'anomaly detection best practices in real-time systems',
    'recommender systems architecting for scalability',
    'time series forecasting production challenges',
    'linear regression mathematical derivation and intuition',
    'logistic regression explained for practical applications',
    'decision trees visual explanation and implementation guide',
    'random forest best practices for robust models',
    'support vector machines (SVM) from scratch implementation',
    'k-nearest neighbors (kNN) practical guide and use cases',
    'naive bayes classifier intuition and real-world examples',
    ]


    scrape_queries(test_queries, num_pages=6)